config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  resources :countries, only: %i[index show]

  get "/pages/:page" => "pages#show", as: :page

  get "/map" => "maps#index"

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], Article
    can [:update, :destroy], Article, user: user
  end
end

app/models/advisory.rb
class Advisory < ApplicationRecord
  belongs_to :country
  belongs_to :issuer
  ransacker :average_advisories do
    Arel.sql('average')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_rich_text :body

  validates :title, :body, presence: true
  validates :title, length: { minimum: 5 }
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :advisories
end

app/models/issuer.rb
class Issuer < ApplicationRecord
  has_many :advisories
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :omniauthable,
         omniauth_providers: [:facebook, :google_oauth2, :github]

  has_one_attached :avatar
  has_many :articles, dependent: :destroy

  def name
    @name ||= self[:name].presence || email.split("@").first
  end

  def self.from_omniauth(auth)
    data = auth.info

    User.where(email: data['email']).first_or_create do |user|
      user.name = data['name']
      user.password = Devise.friendly_token[0,20] if user.new_record?
    end
  end

  protected

  def password_required?
    new_record? || password.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to request.referer || root_path, alert: exception.message
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: :show

 # authorize_resource

  def index
    @q = Country.ransack(params[:q])
    @pagy, @countries = pagy(@q.result.includes(:advisories).order(name: :asc), items: 30)
    @country_info = ISO3166::Country[@country]
    @regions = ISO3166::Data.cache.map {|_,v| v['region']}.uniq.sort.delete_if(&:blank?)
  end

  def show
    @country_info = ISO3166::Country[@country.alpha2]
    @advisories = Advisory.where(country: @country).order(pub_date: :desc)
  end

  private

  def set_country
    @country = Country.find_by(alpha2: params[:id])
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @countries = Country.all
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
    @country = Country.find_by(alpha2: (params[:country]))
    @country_info = ISO3166::Country[params[:country]]
    @advisories = Advisory.where(country: @country).order(pub_date: :desc)
  end

end

def user_params
  params.require(:maps).permit(:country)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
    @country = Country.find_by(alpha2: params[:country])
  rescue ActionView::MissingTemplate
    render "errors/not_found", status: 404
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    omniauth_callback('Google', 'google_data')
  end

  def github
    omniauth_callback('GitHub', 'github_data')
  end

  def facebook
    omniauth_callback('Facebook', 'facebook_data')
  end

  private

  def omniauth_callback(kind, session_key)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{session_key}"] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = User.ransack(params[:q])
    @pagy, @users = pagy(@q.result.order(created_at: :desc), items: 5)
  end

  def show
    @user = User.find(params[:id])

    render layout: false
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user, notice: "Account was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy

    redirect_to root_path, notice: "Account was successfully deleted."
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  include Heroicon::Engine.helpers

  def page_title
    "advisory.travel | #{controller_name.humanize} | Travel advisories for countries around the world"
  end

  def body_class
    "#{controller_name}-#{action_name}"
  end

  def nav_link_class(section, extra = nil)
    if section == controller_name
      "bg-amber-900 text-white px-3 py-2 rounded-md text-sm font-medium #{extra}"
    else
      "text-amber-300 hover:bg-amber-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium #{extra}"
    end
  end

  def get_emoji_flag(alpha2)
    return ISO3166::Country[alpha2].emoji_flag
  end

  def time_ago(time_object)
    "#{time_ago_in_words(time_object)} ago"
  end

  def format_time(time_object)
    l(time_object, format: :long)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def author_and_date(article)
    "by #{article.user.name} | #{format_time(article.created_at.to_date)}"
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
  def advisory_level(advisory)
    case advisory
    when 1
      return advise = { name: "Normal Precautions", color: "bg-green-400" }
    when 2
      return advise = { name: "Increased Caution", color: "bg-yellow-400" }
    when 3
      return advise = { name: "Reconsider Travel", color: "bg-orange-400" }
    when 4
      return advise = { name: "Do Not Travel", color: "bg-red-400" }
    else
      return advise = { name: "—", color: "bg-gray-200" }
    end
  end

  def advisory_level_fraction(advisory)
    return "<sup>#{advisory.level}</sup>&#x2044;<sub>4</sub>"
  end
end

def issuer_info(alpha2)
  case alpha2
  when "CA"
    issue_info = { gov: "Government of Canada", flag: "🇨🇦" }
  when "US"
    issue_info = { gov: "United States Department of State", flag: "🇺🇸" }
  else
    "—"
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size = 40)
    image_tag avatar_url(user, size),
      size: size,
      class: "rounded-full"
  end

  def avatar_url(user, size)
    if user.avatar.attached?
      url_for(user.avatar)
    else
      gravatar_url(user.email, size)
    end
  end

  def gravatar_url(email, size)
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    gravatar_options = {
      s: size,
      d: "retro"
    }

    "https://www.gravatar.com/avatar/#{gravatar_id}?#{gravatar_options.to_param}"
  end
end

app/views/application/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="my-4 p-4 bg-red-600 text-white rounded">
    <b class="text-xl"><%= pluralize(object.errors.count, "error") %> found:</b>

    <ul class="list-none">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="flex items-center justify-between px-8 py-4 bg-amber-100">
    <%= msg %>
    <button onclick="closeFlashAlert()"><%= heroicon "x-mark" %></button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="mx-auto mt-16 w-full max-w-container px-4 sm:px-6 lg:px-8">
  <div class="border-t border-slate-900/5 py-5">
    <p class="mt-4 text-center text-sm leading-6 text-slate-500">© <%= Time.now.year %> <a href="https://joe.depumpo.com" target="_blank">Joe DePumpo</a></p>
    <!--
    <div class="mt-4 flex items-center justify-center space-x-4 text-sm font-semibold leading-6">
      <%= link_to "About us", page_path(:about) %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Terms", page_path(:terms) %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Privacy policy", page_path(:privacy_policy) %>
    </div>
    -->
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="bg-amber-800" role="navigation">
  <div class="mx-auto px-6 md:px-12">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <a href="<%= root_path %>" class="text-white text-2xl">🌍 advisory.travel</h2>
        </div>
        <div class="hidden sm:block">
          <div class=" relative ml-8 flex items-baseline space-x-4">
            <a href="<%= root_path %>" class="<%= nav_link_class("home") %>">Home</a>
            <a href="<%= countries_path %>" class="<%= nav_link_class("countries") %>">Countries</a>
            <div class="relative">
              <a href="<%= map_path %>" class="<%= nav_link_class("maps") %>">Map</a>
              <small class="text-xs text-white font-medium bg-red-600 rounded-lg px-1 py-0.5 absolute -top-3 left-8">NEW</small>
            </div>
          </div>
        </div>
      </div>
      <!--
      <div class="hidden sm:block">
        <div class="ml-4 flex items-center md:ml-6">
          <div class="relative ml-3">
            <% if user_signed_in? %>
              <a href="<%= edit_user_path %>" class="flex max-w-xs items-center rounded-full bg-amber-800 text-sm">
                <%= avatar(current_user) %>
              </a>
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "text-amber-300 hover:bg-amber-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
          </div>
        </div>
      </div>
      -->
      <div class="sm:hidden">
        <button class="<%= nav_link_class(nil) %>" onclick="toggleMenu()">
          <%= heroicon "bars-3" %>
        </button>
      </div>
    </div>
  </div>

  <div class="sm:hidden hidden mobile-menu">
    <div class="space-y-2 px-2 pb-3 sm:px-3">
      <a href="<%= root_path %>" class="<%= nav_link_class("home", "block") %>">Home</a>
      <a href="<%= countries_path %>" class="<%= nav_link_class("countries", "block") %>">Countries</a>
      <a href="<%= map_path %>" class="<%= nav_link_class("maps", "block") %>">Map</a>
      <!--
      <% unless user_signed_in? %>
        <a href="<%= new_user_session_path %>" class="<%= nav_link_class(nil, "block") %>">Sign in</a>
      <% end %>
      -->
    </div>
    <!--
    <% if user_signed_in? %>
      <div class="border-t border-amber-700 py-4">
        <a href="<%= edit_user_path %>">
          <div class="flex items-center px-5">
            <div class="flex-shrink-0">
              <%= avatar(current_user) %>
            </div>
            <div class="ml-3">
              <div class="text-base font-medium leading-none text-white"><%= current_user.name %></div>
              <div class="text-sm font-medium leading-none text-amber-400"><%= current_user.email %></div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
    -->
  </div>
</nav>

app/views/application/_remote_modal.html.erb
<div class="modal" id="remote-modal" aria-hidden="true">
  <div class="modal-overlay" tabindex="-1" data-micromodal-close>
    <div class="modal-container" role="dialog">
      <header class="flex items-center justify-between">
        <h1 class="modal-title"></h1>
        <button class="outline-none" data-micromodal-close>
          <%= heroicon "x-mark", options: { class: "w-8 h-8" } %>
        </button>
      </header>
      <main class="my-2">
        <p>Loading ...</p>
      </main>
    </div>
  </div>
</div>

app/views/countries/index.html.erb
<% content_for :meta_title, "Countries | #{DEFAULT_META["meta_name"]} | #{DEFAULT_META["meta_description"]}" %>
<h1>Countries</h1>

<%= search_form_for @q, data: { turbo_frame: "search" } do |f| %>
  <div class="grid grid-cols-2 grid-rows-2 md:grid-cols-4 md:grid-rows-1 gap-3">
    <div class="relative col-span-2 justify-stretch">
      <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <%= heroicon "magnifying-glass" %>
      </div>
      <%= f.text_field :name_cont, class: "search-input p-3 pl-10 text-sm", onkeyup: "search()", placeholder: "Country Name" %>
    </div>
    <div class="relative">
      <div class="flex absolute inset-y-1 left-0 items-center pl-3 pointer-events-none">
        <%= heroicon "globe-alt" %>
      </div>
      <%= f.select :region_eq, @regions, { include_blank: "World" }, { class: "region-input p-3 pl-10 text-sm", onchange: "search()" } %>
    </div>
    <div class="relative">
      <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <%= heroicon "flag" %>
      </div>
      <%= f.select :advisories_level_eq, [["Normal Precautions", 1], ["Increased Caution", 2], ["Reconsider Travel", 3], ["Do Not Travel", 4]], { include_blank: "All Levels" }, { class: "level-input p-3 pl-10 text-sm", onchange: "search()" } %>
    </div>
  </div>
<% end %>

<%= turbo_frame_tag "search", target: "_top" do %>
  <div class="mt-8 widetable">
    <table>
      <thead>
        <tr>
          <th scope="col" class="w-2"><!--Country Flag--></th>
          <th scope="col"><%= sort_link(@q, :name) %></th>
          <th scope="col"><%= sort_link(@q, :region) %></th>
          <th scope="col" class="text-center"><%= sort_link(@q, :advisories_level) %></th>
        </tr>
      </thead>
      <tbody>
        <% @countries.each do |country| %>
          <tr style="cursor: pointer; cursor: hand;" onclick="window.location='<%= country_path(country.alpha2) %>';">
            <td class="w-2">
              <%= link_to get_emoji_flag(country.alpha2), country_path(country.alpha2) %>
            </td>
            <td>
              <%= link_to country.name, country_path(country.alpha2), class: "text-amber-900 outline-none font-bold" %>
            </td>
            <td>
              <%= country.region %>
            </td>
            <td class="text-center">
              <% advisory_level = country.advisories.average(:level).to_i %>
              <span class="px-4 py-2 rounded inline-block <%= advisory_level(advisory_level)[:color] %>">
                <%= advisory_level(advisory_level)[:name] %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="text-center mt-10">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/countries/partials/_country_summary.html.erb
<h1 class="card-title"><%= country_info.emoji_flag %> <%= country.name %></h1>

<div class="card-body">
  <% unless current_page?(map_path) %>
    <div id="map"
      class="h-64 w-full"
      data-show-map="true"
      data-country-min-lat="<%= @country_info.min_latitude %>"
      data-country-min-long="<%= @country_info.min_longitude %>"
      data-country-max-lat="<%= @country_info.max_latitude %>"
      data-country-max-long="<%= @country_info.max_longitude %>">
    </div>
  <% end %>
  <dl>
    <dt class="font-semibold mt-2">Capital</dt>
    <dd><%= @country.capital %></dd>
    <dt class="font-semibold mt-2">Currency</dt>
    <dd>
      <span class="font-semibold text-white bg-slate-700 px-1 rounded"><%= "#{@country_info.currency.symbol}" %></span>
      <%= "#{@country_info.currency.name} (#{@country_info.currency.iso_code})" %>
    </dd>
    <dt class="font-semibold mt-2">Drives on the</dt>
    <dd><%= @country.drives_on.capitalize %></dd>
    <dt class="font-semibold mt-2">Population</dt>
    <dd>~ <%= number_to_human(@country.population) %></dd>
  </dl>
</div>

app/views/countries/partials/advisories/_advisory.html.erb
<div class="mb-5 p-2 bg-slate-100 rounded">
  <details class="group">
    <summary class="font-medium cursor-pointer list-none">
      <section class="grid grid-cols-2 md:grid-cols-3 md:grid-rows-auto gap-2 items-center">
        <span class="col-span-3 md:col-span-1 p-2 rounded font-semibold text-center <%= advisory_level(advisory.level)[:color] %>"><%= advisory_level(advisory.level)[:name] %></span>
        <p class="col-span-1 justify-self-center"><%= heroicon "calendar" %> <%= time_ago(advisory.pub_date) %></p>
        <div>
          <p class="col-span-1 text-center"> <span class="inline" alt="<%= issuer_info(advisory.issuer[:name])[:gov] %>" data-tippy-content="<%= issuer_info(advisory.issuer[:name])[:gov] %>">Issued by <%= issuer_info(advisory.issuer[:name])[:flag] %></span></p>
        </div>
        <% if advisory.body.present? %>
        <section class="col-span-3 line-clamp-3 group-open:line-clamp-none text-neutral-600 mt-3 list-dot list-inside">
          <p><%= advisory.body.html_safe %></p>
        </section>
        <span class="col-span-3 bg-slate-200 rounded p-2 flex flex-row">
          <span class="group-open:hidden">View More</span>
          <span class="hidden group-open:block">View Less</span>
          <span class="transition group-open:rotate-180">
            <svg fill="none" height="30" shape-rendering="geometricPrecision" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" width="24"><path d="M6 9l6 6 6-6"></path>
            </svg>
          </span>
        </span>
        <% end %>
      </section>
    </summary>
  </details>
</div>

app/views/countries/partials/advisories/_avg_advisory.html.erb
<div class="rounded p-4 mb-4 <%= advisory_level(advisory.average(:level).to_i)[:color] %>">
  <span class="font-semibold text-center"><%= advisory_level(advisory.average(:level).to_i)[:name] %></span>
  <p>There are currently <%= advisory.count %> active travel advisories for <%= @country.name %>.</p>
  <p>The most recent advisory was issued <%= time_ago(advisory.first.pub_date) %> by <span alt="<%= issuer_info(advisory.first.issuer[:name])[:gov] %>" data-tippy-content="<%= issuer_info(advisory.first.issuer[:name])[:gov] %>"><%= issuer_info(advisory.first.issuer[:name])[:flag] %></span>, which recommended <span class="font-medium"><%= advisory_level(advisory.first.level)[:name] %></span>.</p>
</div>

app/views/countries/partials/advisories/_no_advisory.html.erb
<section class="card-body">
  <p class="px-4 py-2 rounded bg-gray-200">
    No advisories are currently available. This could be for a variety of reasons, including how the US Department of State categorizes and releases travel advisories. We are working to expand the sources of our travel advisories and country coverage.
  </p>
</section>

app/views/countries/show.html.erb
<% content_for :meta_title, "#{@country.name} Travel Advisories | #{DEFAULT_META["meta_name"]} | #{DEFAULT_META["meta_description"]}" %>

<%= link_to "World", countries_path %> &gt; <%= link_to @country.region, countries_path("q[region_start]": @country.region) %> &gt; <%= link_to @country_info.subregion, countries_path("q[subregion_start]": @country.subregion) %> &gt; <%= @country.name %>

<div class="grid grid-flow-row md:grid-flow-col md:grid-cols-3 gap-2 md:gap-4">
  <div class="card my-4 col-span-2 md:col-span-1">
    <%= render partial: "/countries/partials/country_summary", locals: { country: @country, country_info: @country_info } %>
  </div>
  <div class="grid grid-flow-row col-span-2">
    <section class="card my-4">
      <h2>Travel Advisories</h2>
      <% if @advisories.present? %>
        <div>
          <%= render partial: "countries/partials/advisories/avg_advisory", locals: { advisory: @advisories } %>
        </div>
        <hr />
        <div class="grid divide-y divide-neutral-200 mt-8">
          <%= render partial: "countries/partials/advisories/advisory", collection: @advisories %>
        </div>
      <% else %>
        <%= render "countries/partials/advisories/no_advisory" %>
      <% end %>
    </section>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex flex-col text-center my-24 items-center">
  <h1 class="tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
    <span>Travel advisories,</span><br>
    <span class="text-amber-700">global and updated daily.</span>
  </h1>

  <p class="mt-5 mb-10 m-auto max-w-3xl text-gray-500 sm:text-lg md:text-xl">advisory.travel collects travel advisories for nearly every country in the world. We continuously update our advisories so that you always have the latest information available.</p>

  <section class="flex flex-col gap-3 md:flex-row md:gap-6 items-center justify-items-between">
    <%= link_to "All Countries", countries_path, class: "btn" %>
    <section>
      <label class="hidden" for="country_selector">Select a Country</label>
      <select class="btn btn-outline max-w-xs md:max-w-sm" id="country_selector" onchange="const elem = document.getElementById('country_selector'); window.location = (elem.value);">
        <option>Select a Country</option>
        <% @countries.order(name: :asc).each do |country| %>
          <option id="country" value="<%= country_path(country.alpha2) %>"><%= country.name %> <%= get_emoji_flag(country.alpha2) %></option>
        <% end %>
      </select>
    </section>
  </section>
</div>

app/views/maps/index.html.erb
<div id="map_container" class="sidebar_closed h-min">
  <section id="map_card" class="h-min my-2">
    <div class="flex bg-slate-300 rounded-t p-4 text-sm text-slate-700">
      <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <div>
          <span class="font-medium">Select a country</span> to view latest advisories.
      </div>
    </div>

    <div id="map"
      class="h-[50vh] md:h-[75vh] w-full relative"
      data-show-map="true"
      data-world-advisory-map="true">
      <div id="loading-background" class="absolute z-10 flex inset-0 bg-slate-600/50">
        <p id="spinner" class="absolute text-center top-1/2 left-1/2 right-1/2 z-20 text-4xl text-amber-800 animate-bounce"><%= heroicon "sparkles", options: { class: "h-12 w-12"} %></p>
      </div>
    </div>

    <div class="flex flex-wrap gap-2 md:flex-row md:gap-x-4 bg-slate-300 rounded-b p-2 text-sm text-slate-700 justify-center items-center">
      <span class="bg-[#228b22]/50 p-2 rounded font-semibold">No Advisory</span>
      <span class="bg-[#ffd800]/50 p-2 rounded font-semibold">Exercise Caution</span>
      <span class="bg-[#ff8c00]/50 p-2 rounded font-semibold">Reconsider Travel</span>
      <span class="bg-[#ae0c00]/50 p-2 rounded font-semibold">Do Not Travel</span>
    </div>
  </section>

  <%= turbo_frame_tag "country_info" do %>
    <% if params[:country] %>
      <section class="items-stretch card my-2 rounded-lg sm:rounded">
      <div id="sidebar_container" class="closed">
        <div class="flex justify-end">
          <button onClick="
          const grid = document.getElementById('map_container');
          grid.classList.replace('sidebar_open', 'sidebar_closed');
          const frame = document.getElementById('country_info');
          frame.innerHTML = '';"
          class="p-2 rounded bg-slate-300"><%= heroicon "x-circle", options: { class: "text-slate-700 text-2xl block" } %></button>
        </div>
      </div>
      <% if @country %>
        <%= render partial: "/countries/partials/country_summary", locals: { country: @country, country_info: @country_info } %>
        <% if @advisories.present? %>
        <hr class="mt-8">
          <div class="grid divide-y divide-neutral-200 mt-8">
            <%= render partial: "countries/partials/advisories/avg_advisory", locals: { advisory: @advisories } %>
            <a class="p-3 rounded no-underline bg-amber-800 text-center font-bold text-white" target="_top" href="<%= country_path(@country.alpha2) %>">See All Advisories</a>
          </div>
        <% else %>
          <%= render "countries/partials/advisories/no_advisory" %>
        <% end %>
      <% else %>
        <%= render "countries/partials/advisories/no_advisory" %>
      <% end %>
      </section>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>My account</h1>

<%= form_with(model: current_user) do |form| %>
  <%= render "application/error_messages", object: current_user %>

  <div class="mb-4">
    <%= avatar(current_user, 200) %>
  </div>

  <div>
    <%= form.label :avatar %>
    <%= form.file_field :avatar, accept: "image/*" %>
  </div>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= form.submit nil, class: 'btn' %>
  </div>
<% end %>

<div class="mt-8">
  <p>Sign out from my account.</p>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline" %>
</div>

<div class="mt-8">
  <p>Be careful! This action is irreversible.</p>
  <%= button_to "Delete my account", user_path(current_user), method: :delete, class: "btn btn-danger" %>
</div>